# Generated by Django 5.2 on 2025-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0004_rename_service_serviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialIfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('count_rating', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=150)),
                ('description_review', models.TextField()),
            ],
        ),
    ]
