# Generated by Django 5.2 on 2025-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0005_testimonialifor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialifor',
            name='count_rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
