# Generated by Django 5.2 on 2025-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0006_alter_testimonialifor_count_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestionsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
