# Generated by Django 5.2 on 2025-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0008_bloginfo_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
