# Generated by Django 5.2 on 2025-05-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0010_authorinfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwebsite.authorinfor'),
        ),
    ]
