# Generated by Django 5.2 on 2025-05-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0011_alter_bloginfo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfo',
            name='author',
        ),
    ]
