# Generated by Django 5.2 on 2025-05-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0012_remove_bloginfo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appwebsite.authorinfor'),
        ),
    ]
