# Generated by Django 5.2 on 2025-05-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0013_bloginfo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='topic',
            new_name='topic_category',
        ),
    ]
